---
title: Set Hidden Pages
description: Hides Settings pages that are either broken or unused
privilege: TrustedInstaller
actions:
    # https://learn.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app

    # Windows 10
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'SettingsPageVisibility'
    data: 'hide:recovery;autoplay;usb;maps;maps-downloadmaps;findmydevice;privacy-speechtyping;privacy-speech;privacy-feedback;privacy-activityhistory;privacy-location;privacy-general;sync;cortana-windowssearch;mobile-devices;mobile-devices-addphone;backup;'
    type: REG_SZ
    builds: [ '!>=22000' ]

    # Windows 11
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'SettingsPageVisibility'
    data: 'hide:recovery;autoplay;usb;maps;maps-downloadmaps;findmydevice;privacy-speechtyping;privacy-speech;privacy-feedback;privacy-activityhistory;privacy-location;privacy-general;sync;cortana-windowssearch;mobile-devices;mobile-devices-addphone;family-group;deviceusage;'
    type: REG_SZ
    builds: [ '>=22000' ]
